kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cephfs
provisioner: ceph.com/cephfs
parameters:
    monitors: 172.18.88.200:6789,172.18.88.201:6789,172.18.88.202:6789
    adminId: k8s
    adminSecretName: ceph-admin-secret
    adminSecretNamespace: cephfs
    claimRoot: /volumes/kubernetes

